name: Build And Run Java
# events
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clone repo to run operation
      - name: Set up # set up programming language version
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt' 

      - name: Build # Build class files or compile code
        run: cd src && javac Main.java
        shell: bash

      - name: Run
        run: cd src && java Main
        shell: bash
      
      - name: Successfull Notification
        uses: AlexisMateo/sendmail-action@5
        with:
          # smtp://mail4tahsin@gmail.com:@smtp.gmail.com:465
          smtp-server: ${{ secrets.SMTP_SERVER }}
          smtp-server-port: ${{ secrets.STMP_PORT }}
          auth-user: ${{ secrets.EMAIL_USER }}
          auth-password: ${{secrets.EMAIL_PASSWORD }}
          subject: correciones a ${{github.repository}}
          
          body: ${{github.repository}} ran successful build
          from: ${{ secrets.EMAIL_USER }}
          to: fullstackltd@gmail.com
          is-tls: false
          commit-message: true
          

      