name: Build And Run Java
# events
on:
  push:
    branches:
      - main
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clone repo to run operation
      - name: Set up # set up programming language version
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt' 

      - name: Build # Build class files or compile code
        run: cd src && javac Main.java
        shell: bash

      - name: Run
        run: cd src && java Main
        shell: bash
      
      - name: Successfull Notification
        uses: dawidd6/action-send-mail@v3
        with:
          # smtp://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_port: 465
          secure: true
          subject: Full Stack Actions Build Success
          # mail4tahsin@gmail.com
          # tahsin@fullstackbd.com
          # tahsinayman@hotmail.com
          to: nusrattoha24@gmail.com,fullstackltd@gmail.com
          from: Tahsin Ayman
          body: Build job of ${{github.repository}} completed successfully!
          

      