name: Testing Secrets
on:
  workflow_dispatch:
jobs:
  test_env:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Name
        run: echo ${{ secrets.NAME }}
        # get environment secrets and
        # log it on the console for testing
